_core:
  default_config_hash: hjgcuHpcsme6SW-7MKpZm3bhnR76f1yX2Y8Xe0STesw
drupalAcctProvisionServer: osha
ldapEntryProvisionServer: null
drupalAcctProvisionTriggers:
  - drupal_on_login
  - drupal_on_update_create
ldapEntryProvisionTriggers: {  }
orphanedDrupalAcctBehavior: user_cancel_block
orphanedCheckQty: 100
orphanedAccountCheckInterval: weekly
userConflictResolve: resolve
manualAccountConflict: conflict_associate
acctCreation: ldap_behaviour
disableAdminPasswordField: false
userUpdateCronQuery: people
userUpdateCronInterval: always
ldapUserSyncMappings: {  }
